@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1_AR76668 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Wed Feb 09 19:57:41 +0000 2022
REM SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
REM
REM IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto b96a6ce7e0d942cca62cf24e11f49fc3 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_idelay_behav xil_defaultlib.tb_idelay -log elaborate.log"
call xelab  -wto b96a6ce7e0d942cca62cf24e11f49fc3 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_idelay_behav xil_defaultlib.tb_idelay -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
